name: Build WASM

on:
  push:
    branches:
      - master  # 合适的主分支
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git checkout 1.39.9
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
      - name: Makefile
        run: |
          mkdir build
          mkdir -p dist/wasm
          cd interpreter
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: webmpc-${{ matrix.os }}
          path: dist/wasm*